<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>如何中断 Promise 链</title>
</head>
<body>
<script>
  let p = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve('OK');
      // reject('Err');
    }, 1000);
  });
  p.then(value => {
    console.log(111);
    // throw '失败啦!';
    /*
     * 中断链
     * 有且只有一种方式
     */
      return new Promise(() => {}); // 返回 pending 状态的 Promise 对象
  }).then(value => { // 不需要给下面两个 then 指定失败的回调函数, 因为会穿透使用到catch
    console.log(222);
  }).then(value => {
    console.log(333);
  }).catch(reason => {
    console.warn(reason);
  });
</script>
</body>
</html>